version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: shop_sphere_backend_jenkins
    ports:
      - "3100:3000"  # Changed to avoid clash with prod
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGODB_URI=mongodb+srv://rumerjaved7:nZlh8VxWpiANvjh5@cluster0.dqasiyv.mongodb.net/ShopSphere?retryWrites=true&w=majority
    volumes:
      - ./server:/app
    networks:
      - shop-sphere-ci-network

  frontend:
    build:
      context: ./my-project
      dockerfile: Dockerfile
    container_name: shop_sphere_frontend_jenkins
    ports:
      - "5100:5000"  # Changed to avoid clash with prod
    environment:
      - NODE_ENV=production
      - PORT=5000
    depends_on:
      - server
    volumes:
      - ./my-project:/app
    networks:
      - shop-sphere-ci-network

networks:
  shop-sphere-ci-network:
    driver: bridge

