version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/ecommerce # Changed to match the service name
    depends_on:
      - mongo
    networks:
      - mern-network

  frontend:
    build:
      context: ./my-project
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - server
    networks:
      - mern-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - mern-network

networks:
  mern-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
