version: '3.8'
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: shop_sphere_backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      - ./server:/app
    networks:
      - shop-sphere-network

  frontend:
    build:
      context: ./my-project
      dockerfile: Dockerfile
    container_name: shop_sphere_frontend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
    volumes:
      - ./my-project:/app
    depends_on:
      - server
    networks:
      - shop-sphere-network

networks:
  shop-sphere-network:
    driver: bridge